language: go

go:
  - 1.9

install:
  - go get -t -v ./...<% if (cli) { %>
  - go get -v github.com/mitchellh/gox

script:
  - chmod +x ./build.sh
  - make build<% } %>
<% if (autobuild) { %>
deploy:
  provider: releases
  api_key:
    secure: "put your github encrypted token here"
  file: bin/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: <%= username %>/<%= name %>
<% } %>
